# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate Cypress Report

on:
  push:
    branches:
      - 'main'

jobs:
  cypress-test:
    name: Run on Chrome 100
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    steps:
    - uses: actions/checkout@v3
    
    - name: Install and Verify
      run: |
        npm ci
        $(npm bin)/cypress verify
    
    - name: Run all Cypress tests
      run: npm run cy:run:dashboard
      continue-on-error: false
    
    - name: Copy test executions videos and screenshots
      run: |
        mkdir public
        cp -r cypress/videos public/videos
        cp -r cypress/screenshots public/screenshots
    
    - name: Merge test reports
      run: npm run combine-reports
      
    - name: Generate HTML report
      run: npm run generate-report
      
    - name: Deploy report page to Github page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
